### PR TITLE
correct table name and column name

### PR DESCRIPTION
**Pull request by hafizmsuleman**

### CODE REVIEW

**Comment by SireInsectus** [comment]
@hafizmsuleman We don't accept pull requests but rather ask that any changes be made directly in the Curriculum-Dev workspace.

**Comment by hafizmsuleman** [comment]
whom to ask ?

**Comment by fbartonaiimi** [comment]
@SireInsectus You broke this repo when you made commit 677c25e37cd4361cff1b441c144b447bc07d588c 14 hours ago. Release 2.2.2 is still working but you can't complete the tutorials if you import the repo (pull from master) in Databricks

**Comment by SireInsectus** [comment]
We/I fixed the problem several hours ago.

**Comment by SireInsectus** [comment]
Sorry about that.

**Pull request closed without merging**
